### ISSUE TITLE
Feature request: Export PDFs

### ISSUE THREAD

**Issue by ultinate** [playniuniu/docker-jupyter-pandas#2]
I would like to export PDFs from JupyterLab. We probably need these:
* nbconvert (installed already, dependency of ?)
* Pandocs, https://pandoc.org/installing.html
* TeX (XeLaTeX), 

From: https://nbconvert.readthedocs.io/en/latest/install.html

**Comment by playniuniu** [comment]
export pdf have some problems with alpine base image

I wonder keep small image so ignore this problem

If you wonder use this feature, the workaround is to save to html and then convert to pdf

or you can change the base image to debian and install it your self
